version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=sec.settings
      - SQLURL=postgresql://postgres:root@db:5432/db
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    restart: always