
name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t your_image_name .
          docker tag your_image_name ${{ secrets.DOCKER_USERNAME }}/your_image_name
          docker push ${{ secrets.DOCKER_USERNAME }}/your_image_name

      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_APP_ID: ${{ secrets.RENDER_APP_ID }}
        run: |
          curl -X POST \
          https://api.render.com/v1/apps/${RENDER_APP_ID}/deploys \
          -H 'Authorization: Bearer ${RENDER_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"commit": "${GITHUB_SHA}"}'
