name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest . # Используем имя репозитория как имя образа
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Deploy to Render
        env:
          RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
          RENDER_WEB_SERVICE_ID: ${{ secrets.RENDER_WEB_SERVICE_ID }} # Или RENDER_SERVICE_ID
        run: |
          curl -X POST \
          https://api.render.com/v1/services/${RENDER_WEB_SERVICE_ID}/deploys \
          -H 'Authorization: Bearer ${RENDER_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"clearCache": "do_not_clear"}'
