# Generated by Django 4.2.13 on 2024-11-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='good',
        ),
    ]
