# Generated by Django 5.1.3 on 2024-12-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='timecreation',
            field=models.DateTimeField(auto_created=True, verbose_name='Время добавления'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
